### ISSUE TITLE
table 中按 tab 键切，光标应换到下一个单元格

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#114]
## 功能描述

如题。

## 提炼几个功能点

- 当光标在 table 时
- 按 tab 键
- 应该跳到下一个单元格

## 原型图

无

## 可参考的案例

无

**Comment by shi-lai-mu** [comment]
遗留问题记录：
- 光标在文字中间，按 tab 会全选文字
- 如果下一个单元格有文本，按 tab 会选中下一个单元格的文本
