### ISSUE TITLE
v5 不支持 shadowDOM

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#115]
## 问题描述

如题，测试 v5 是否可用于 shadowDOM

## wangEditor 版本

v5

**Comment by wangfupeng1988** [comment]
参考 slate.js 的 shadowDOM 即可

**Comment by clinfc** [comment]
![QQ截图20210823172914](https://user-images.githubusercontent.com/39868400/130425776-1e0896ee-92ba-4ab0-80d4-a53033e4241d.png)
![微信截图_20210823173654](https://user-images.githubusercontent.com/39868400/130425813-d7800174-25ee-45c9-bd5f-fb2bbd4e34a5.png)

**Comment by wangfupeng1988** [comment]
感谢小方测试，后面作为一个 bug 处理，我再安排人。
