### ISSUE TITLE
【测试】v5 是否可用于 electron ？

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#117]
## 问题描述

如题。测试 v5 是否可用于 electron

## wangEditor 版本

v5

**Comment by a835100635** [comment]
v5 可正常用于 electron（原生）
![image](https://user-images.githubusercontent.com/65208676/130321817-ad330599-3aed-4e22-8cc8-299ba4ea3a58.png)

**Comment by a835100635** [comment]
1、分割线能点击并且获得焦点并且输入内容，但是立马会被删除内容
![image](https://user-images.githubusercontent.com/65208676/130322139-86055bf2-f888-4bec-9251-7cf567f38935.png)
2、全选删除 (https://github.com/wangeditor-team/we-2021/issues/99)  缩进和布局方式样式未删除
3、清除格式 (https://github.com/wangeditor-team/we-2021/issues/98) 居中和缩进时 样式没有被清除

**Comment by a835100635** [comment]
electron（原生）使用基本就是在谷歌浏览器上运行wangeitor一致

**Comment by a835100635** [comment]
demo链接：https://github.com/a835100635/we-2021-electron-test
