### ISSUE TITLE
【测试】和 jquery.validate 插件是否有冲突

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#121]
## 问题描述

如题。测试和  jquery.validate 插件是否有冲突 ？

## wangEditor 版本

v5

**Comment by wangfupeng1988** [comment]
html 创建一个 form 表单，编辑器放在表单里，将内容实时同步到一个 textarea
能正常 submit 表单即可。

注意，是 submit ，不是 js 获取值然后 ajax 提交

**Comment by shi-lai-mu** [comment]
使用 jquery 3.6 + jquery-validate 1.19.3 原生写法，使用form submit提交测试通过

- 使用submit提交后value正常
- 编辑器正常运行使用无冲突报错等
- 编辑器字段必填校验正常
- 
[demo链接](https://github.com/shi-lai-mu/wangEditor/tree/demo/wangeditor-v5-JQuery-validate)
