### ISSUE TITLE
【测试】和各个 UI 框架是否有样式冲突 & 用于 dialog

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#122]
## 问题描述

如题。测试用于 antd element layui bootstrap 这些 UI 框架，是否有样式冲突？

还有，如果这些 UI 中有 dialog 功能，则在 dialog 生成编辑器，看是否有影响

## wangEditor 版本

v5

**Comment by leohai** [comment]
element-ui dialog 里点击全屏，编辑器整体会向右偏移距离
<img width="1358" alt="截屏2021-08-29 上午11 41 46" src="https://user-images.githubusercontent.com/34530234/131237555-2a2b910f-3b42-4c69-9728-875785bc50ec.png">
<img width="1225" alt="截屏2021-08-29 上午11 42 38" src="https://user-images.githubusercontent.com/34530234/131237561-524b86d1-9695-4af8-a3bf-2cc7753af388.png">

**Comment by leohai** [comment]
antd modal组件内嵌editor 打开后报错
<img width="1413" alt="截屏2021-08-29 下午4 33 22" src="https://user-images.githubusercontent.com/34530234/131244156-12dccb12-5442-4055-bffb-12f56aab82c0.png">
且编辑器全屏后modal按钮区域样式错乱
<img width="1426" alt="截屏2021-08-29 下午4 34 42" src="https://user-images.githubusercontent.com/34530234/131244202-8b78acf9-ca43-4a38-a76d-0b5d672fc982.png">

**Comment by wangfupeng1988** [comment]
antd modal 的报错，是 antd 自己的问题，和编辑器无关
https://github.com/ant-design/ant-design/issues/22493 这里有解决方案

**Comment by leohai** [comment]
elementUI dialog 中，全屏的偏移问题重现方法
![image](https://user-images.githubusercontent.com/34530234/131673003-92b1cbd6-d376-4d5e-bd7d-0958583cf288.png)
