### ISSUE TITLE
只剩列表符号时删除，光标会到上一个列表项末尾

### ISSUE THREAD

**Issue by leohai** [wangeditor-team/we-2021#123]
## 问题描述

*只剩列表符号时删除，光标会到上一个列表项末尾*

## wangEditor 版本

*v5* mac chrome 92

## 最小成本的复现步骤

<img width="666" alt="截屏2021-08-11 下午11 02 08" src="https://user-images.githubusercontent.com/34530234/129054602-e1938a55-3c91-46cb-9d65-00853529ff39.png">
<img width="613" alt="截屏2021-08-11 下午11 07 51" src="https://user-images.githubusercontent.com/34530234/129054762-94672582-f9fa-4019-b2dd-26d4155b0154.png">

- 录入超过二行文字的列表
- 删除最后一项的文字，保留列表符号
- 删除符号，光标定位到上一项末尾(预期停留在当前行，且没有列表样式)

**Comment by wangfupeng1988** [comment]
该问题暂不解决。
