### ISSUE TITLE
插入图片时，输入如下 src 会 js 报错

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#127]
## bug 描述

参考这个 bug https://github.com/wangeditor-team/wangEditor/issues/2933

本来是要测试 xss 攻击，结果没复现 xss 攻击，但出现了 js 报错

## 你预期的样子是？

正常插入一个图片。图片可以显示不出来，但不要 js 报错

## 浏览器及版本号

chrome 91

## wangEditor 版本

v5

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- examples/default-mode.html 插入图片
- src 输入 `http://xsstest/<img src="1" onmouseover="alert("xss")>.jpg`
- 会有 js 报错

![image](https://user-images.githubusercontent.com/9583120/129167117-4804d0fc-498d-42ce-9085-fe4985def5c4.png)

**Comment by leohai** [comment]
1. 输入`http://xsstest/<img src="1" onmouseover="alert("xss")>.jpg` ，可以正常插入，但是getHtml 格式化xml时会出现元素属性解析出错
![Uploading 截屏2021-08-16 下午10.49.58.png…]()
<img width="808" alt="截屏2021-08-16 下午10 42 43" src="https://user-images.githubusercontent.com/34530234/129583874-a1e0a569-eb69-4df7-8cea-2e7207d4d3e3.png">
如图，造成元素解析成undefined,导致获取node type 出错
2. 在v4试了下`http://xsstest/<img src="1" onmouseover="alert("xss")>.jpg` 插入图片，并没有出现弹出警告框。所以把链接换为`xss" onmousemove="alert('xss')` 有效
3. 如下图，v4，v5表现不一样， v5把应该是vnode做了一层处理把src里的**"**给转义了，内容全被src给包裹了。
<img width="1075" alt="截屏2021-08-16 下午10 36 42" src="https://user-images.githubusercontent.com/34530234/129584479-db6e53b5-6be9-401f-87f1-d47b3be5407e.png">
<img width="723" alt="截屏2021-08-16 下午10 35 35" src="https://user-images.githubusercontent.com/34530234/129584501-e2c6cadc-d347-470f-9188-fb27c2f46afe.png">
<img width="662" alt="截屏2021-08-16 下午10 59 40" src="https://user-images.githubusercontent.com/34530234/129585407-e0e4ac70-2570-4cae-aab5-2dfe596b00af.png">

**Comment by wangfupeng1988** [comment]
已处理
