### ISSUE TITLE
safari 13.1.3 报错

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/we-2021#139]
## bug 描述

最新pull 的master 分支代码 执行
localhost: 8881/examples/default-mode.html 
chrome 表现正常
safari js 报错, 无法正常使用
![image](https://user-images.githubusercontent.com/20200267/129481914-48973c1d-c8d7-4b8f-b2d5-9ff4170104c5.png)

## 你预期的样子是？
正常使用

*请输入内容……*

## 浏览器及版本号
![image](https://user-images.githubusercontent.com/20200267/129481821-04d234ca-f435-44fe-ab5c-3e2c2a08ff20.png)
![image](https://user-images.githubusercontent.com/20200267/129481846-f9348248-0b74-4127-bd91-8ae81e20e93d.png)

## wangEditor 版本

master 最新代码
## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

Safari 直接 打开 example页面

**Comment by wangfupeng1988** [comment]
试试这个是否报错？
http://106.12.198.214:8882/editor/examples/default-mode.html

**Comment by lichenabson** [comment]
测试机不报错, 关闭此 issue
