### ISSUE TITLE
【测试】 vue2 和 React 组件

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#140]
## 功能描述

如题。

npm 发布的组件
- https://www.npmjs.com/package/@wangeditor/editor-for-react
- https://www.npmjs.com/package/@wangeditor/editor-for-vue

使用说明参考 https://github.com/wangeditor-team/we-2021-doc/blob/main/docs/guide/for-frame.md

PS：vue3 的先不用测试

## 提炼几个功能点

- vue 组件，用于 vue2
- React 组件，用于 class component
- React 组件，用于 Hooks

**Comment by wangfupeng1988** [comment]
vue React 场景特别重要，测试时要把所有功能都过一遍，参考模板 https://wangeditor.yuque.com/wangeditor/gtoqwe/rlaa8q#0yXn

**Comment by leohai** [comment]
vue 模板及 编辑器配置、api测试结果
https://wangeditor.yuque.com/wangeditor/gtoqwe/klb2r5#0yXn
