### ISSUE TITLE
特定情况下，不能取消斜体

### ISSUE THREAD

**Issue by wangqiaoling01** [wangeditor-team/we-2021#141]
## 特定情况下，不能取消斜体

*选中文字如图所示，不能将文字取消斜体。控制台无报错*

<img width="958" alt="image" src="https://user-images.githubusercontent.com/67910349/129522083-7e3fe5b8-8c9d-4926-a1d2-f790105d8c49.png">

## 你预期的样子是？

*可以取消斜体*

## 浏览器及版本号

*Safari 版本14.1.1 (16611.2.7.1.4)*

## wangEditor 版本

*v5*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：输入几行文字
- 步骤二：选中几行文字，拖蓝到未选中的文字的那一行末尾
- 步骤三：执行斜体、取消斜体

**Comment by wangqiaoling01** [comment]
在该情况下，加粗、下划线、删除线都不能取消。

**Comment by wangfupeng1988** [comment]
我发现 chrome 也可以复现

**Comment by leohai** [comment]
<img width="1206" alt="截屏2021-09-12 下午1 13 43" src="https://user-images.githubusercontent.com/34530234/132973105-3e859028-4aa0-4ed9-be32-58593bf34af5.png">
获取当前选区的是否存在样式出问题
