### ISSUE TITLE
拖蓝内容中包含代码块时，控制台报错

### ISSUE THREAD

**Issue by wangqiaoling01** [wangeditor-team/we-2021#142]
## bug 描述

*设置字号，拖蓝内容中包含代码块时，字体操作正常，但是控制台报错*
![image](https://user-images.githubusercontent.com/67910349/129528128-7cf05862-2afe-4194-9523-33a2bbea9bbe.png)

## 你预期的样子是？

*控制台不报错*

## 浏览器及版本号

*Safari 版本14.1.1 (16611.2.7.1.4)*

## wangEditor 版本

*v5*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一: default model -> create
- 步骤二: 拖蓝含有代码块的内容
- 步骤三：对其设置字号

**Comment by wangfupeng1988** [comment]
当选中的有 code-block 时，应该禁用字号、字体等文本操作。

**Comment by wangfupeng1988** [comment]
目前测试机已无报错，暂时关闭吧。
