### ISSUE TITLE
开发 Vue3 组件

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#145]
## 功能描述

如题，开发 Vue3 组件。参考当前的 React 和 Vue2 组件。

- 单独新建一个 github repo
- 开发完之后要发布到 npm ，所以要包括 CI/CD 流程（到时候找我要 NPM_TOKEN）
- npm name 叫做 `@wangeditor/editor-for-vue@next`

**Comment by liuqh0609** [comment]
vue3组件中样式无法自动引入，需要用户手动引入
`@import url(@wangeditor/editor-cattle/dist/css/style.css);`

**Comment by liuqh0609** [comment]
![image](https://user-images.githubusercontent.com/43341115/131242098-55d596e2-efb1-4d69-8258-ce6c8b1da68b.png)
这种分离结构时，全屏功能报错
![image](https://user-images.githubusercontent.com/43341115/131242111-3cb9e09a-b507-4fca-bdbd-d2a8eb0dee71.png)

**Comment by liuqh0609** [comment]
组件已经完成，详情查看[wangEditor-for-vue3](https://github.com/wangeditor-team/wangEditor-for-vue3)
