### ISSUE TITLE
表格单元格中tab键体验问题

### ISSUE THREAD

**Issue by q378532364** [wangeditor-team/we-2021#152]
## bug 描述

表格按tab键，变成了空格

## 你预期的样子是？

表格按tab键，预想应该是跳到右边一个单元格（参考语雀编辑器）

## 系统和浏览器及版本号
wind10 all

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能
## 最小成本的复现步骤

1. 插入表格
2. 在第一个单元中输入文字 然后按下tab

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/we-2021/issues/114 重复了
