### ISSUE TITLE
qq浏览器无法创建编辑器控制台报错

### ISSUE THREAD

**Issue by q378532364** [wangeditor-team/we-2021#153]
## bug 描述

qq浏览器无法创建编辑器控制台报错

## 你预期的样子是？

qq浏览器可以创建编辑器

## 系统和浏览器及版本号
win10
![image](https://user-images.githubusercontent.com/43435489/130324557-aeb0625e-5ecb-4857-99b5-3ee384969aa9.png)

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

本地项目
![image](https://user-images.githubusercontent.com/43435489/130324563-2c75a05c-6c2b-4167-8a3f-d04d8a0432ef.png)

线上环境
![a87622d45ccfacf4dbc5ad518776d91](https://user-images.githubusercontent.com/43435489/130379551-f4105068-53f0-43a3-a0c3-ae9bc70b9e17.png)

**Comment by wangfupeng1988** [comment]
和这个问题一起看 https://github.com/wangeditor-team/we-2021/issues/160
