### ISSUE TITLE
safari 浏览器 create editor 报错

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/we-2021#160]
## bug 描述

访问 http://106.12.198.214:8882/main/examples/default-mode.html
safari 浏览器 create editor 报错

https://user-images.githubusercontent.com/20200267/130355158-c1fa2b17-91d8-4f95-aba7-970f101be3b6.mov

## 你预期的样子是？

正常显示

## 系统和浏览器及版本号

- 操作系统: macos 10.15.7
- 浏览器和版本 safari 13.1.1

## demo 能否复现该 bug ？

能

-

**Comment by wangfupeng1988** [comment]
和这个问题一起排查 https://github.com/wangeditor-team/we-2021/issues/153

**Comment by lichenabson** [comment]
![image](https://user-images.githubusercontent.com/20200267/130359709-468008ee-29a6-4a22-84cf-5f38071f4ad2.png)
