### ISSUE TITLE
执行 editor.blur 不会触发编辑器失焦

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#164]
## bug 描述

如题。

## 你预期的样子是？

会失去焦点

## 系统和浏览器及版本号

- 操作系统 mac
- 浏览器和版本 chrome 91

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 访问 examples/default-mode.html ，创建编辑器
- 编辑器会默认 focus
- 在控制台执行 `editor.blur()` ，并没有让编辑器失焦，也没有 js 报错

**Comment by leohai** [comment]
无法重现

**Comment by leohai** [comment]
无法重现

**Comment by wangfupeng1988** [comment]
在 examples/default-mode.html 页面，加一个按钮，然后绑定事件。

```js
    document.getElementById('btn-blur').addEventListener('click', (e) => {
      e.preventDefault()
      e.stopPropagation()
      console.log('do blur')
      editor.blur()
    })
```

先手动 focus 编辑器，然后点击这个按钮，编辑器是不会 blur 的。

**Comment by leohai** [comment]
<img width="917" alt="截屏2021-09-11 下午11 42 37" src="https://user-images.githubusercontent.com/34530234/132953465-bee7c549-add3-4cab-b6a2-142c3864473f.png">
<img width="1253" alt="截屏2021-09-11 下午11 42 45" src="https://user-images.githubusercontent.com/34530234/132953471-b9ed5c3e-1358-4a5f-9b08-1af25284a293.png">
1. click 事件尽管阻止了默认事件及冒泡，按钮依然会变成activeElement 。mousedown事件才能正常
2. blur执行后,没有触发onchange 进行Toolbar 状态栏更新
