### ISSUE TITLE
选中文字输入时，光标错乱

### ISSUE THREAD

**Issue by wangqiaoling01** [wangeditor-team/we-2021#174]
## bug 描述

*选中文字输入时，光标跑到文本前面去了*
![image](https://user-images.githubusercontent.com/67910349/131301389-011de479-ac13-4b86-ac3e-ec90a621f3d7.png)

## 你预期的样子是？

*光标在选中的文字的地方*

## 系统和浏览器及版本号

- 操作系统：mac
- 浏览器和版本：Google浏览器 版本 92.0.4515.159（正式版本） (arm64)

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：输入一段文字
- 步骤二：选中部分文字
- 步骤三 ：输入中文

**Comment by wangfupeng1988** [comment]
看下是否和 https://github.com/wangeditor-team/we-2021/issues/155 重复了？
