### ISSUE TITLE
[vue] 通过defaultContent初始化的图片，删除报错

### ISSUE THREAD

**Issue by leohai** [wangeditor-team/we-2021#177]
## bug 描述

*通过defaultContent初始化的图片，删除报错*
![image](https://user-images.githubusercontent.com/34530234/131676193-67126fac-087b-4783-9803-0dfa9bb6d1f4.png)

## 你预期的样子是？

*正常删除图片*

## 系统和浏览器及版本号

- widnows
- mac @vue/cli

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 配置defaultContent
```
[
    {
        type: 'paragraph',
        children: [
            { text: '图片' },
            {
                type: 'image',
                src: 'http://www.wangeditor.com/imgs/logo.jpeg',
                children: [{ text: '' }], // void node 要有一个空 text
            },
            { text: 'image' },
        ],
    }
]
```
- 点击图片,按键delete删除

**Comment by wangfupeng1988** [comment]
我试了一下，defaultContent 不能直接使用，需要深拷贝一下。我补充到文档了，你试试
https://www.wangeditor.com/v5/guide/for-frame.html#script
