### ISSUE TITLE
[vue] 使用SlateTransforms.removeNodes(editor) 后出现光标错位

### ISSUE THREAD

**Issue by leohai** [wangeditor-team/we-2021#179]
## bug 描述

*当第一行只有文本时，使用SlateTransforms.removeNodes(editor) api*
*删除文本后， 再聚焦编辑器会出现光标错位，且报错*
![image (1)](https://user-images.githubusercontent.com/34530234/131678395-685625ee-5d82-45df-8f40-625b90721c5d.png)
![image (2)](https://user-images.githubusercontent.com/34530234/131678390-f2f8acb0-ef99-489d-81cb-4ac0be1136f8.png)

## 你预期的样子是？

*正常使用api后，聚焦编辑器光标位置正常*

## 系统和浏览器及版本号

- windows
- chrome 92 @vue/cli

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

- 输入一段文本
- 使用SlateTransforms.removeNodes(editor)进行清空
- 再次聚焦编辑器

**Comment by wangfupeng1988** [comment]
这个问题交给用户去处理吧，我们也不好干预。他要通过 API 把 node 全部删掉，怎么都拦不住。
