### ISSUE TITLE
【文档】content 转换为 html中的代码实际运行时，导致页面卡死

### ISSUE THREAD

**Issue by rsl140** [wangeditor-team/we-2021#180]
## bug 描述

【文档】content 转换为 html中的代码实际运行时，导致页面卡死
![image](https://user-images.githubusercontent.com/7655291/131696397-ac8b7e34-4670-4b4a-af5c-b9ec6bd9dace.png)

## 你预期的样子是？

正常运行

## 系统和浏览器及版本号

- mac
- 版本 91.0.4472.114（正式版本） (x86_64) 谷歌

## wangEditor 版本

"@wangeditor/editor-cattle": "^0.7.8"

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/7655291/131696286-22843ab8-0a75-4a84-8adb-3abee673c6a2.png)

**Comment by wangfupeng1988** [comment]
我复现了，已修复，重新发布了新版，你再试试。

**Comment by rsl140** [comment]
正常了
