### ISSUE TITLE
【文档】hoverbarKeys 按照代码配置控制台报错

### ISSUE THREAD

**Issue by rsl140** [wangeditor-team/we-2021#181]
## bug 描述

hoverbarKeys 按照代码配置控制台报错

## 你预期的样子是？

不报错

## 系统和浏览器及版本号

- mac
- 谷歌 版本 91.0.4472.114（正式版本） (x86_64)

## wangEditor 版本

0.7.10

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/7655291/131857861-ceffbe4d-2958-4573-a2c0-2b09e87d275f.png)

![image](https://user-images.githubusercontent.com/7655291/131857806-70677a35-f61f-4a42-bf6c-a81f1ac87f3f.png)

**Comment by wangfupeng1988** [comment]
这里文档写错了。应该是 `editLink`
改过来了 https://www.wangeditor.com/v5/guide/editor-config.html#hoverbarkeys
