### ISSUE TITLE
[vue]视频插入会报错

### ISSUE THREAD

**Issue by leohai** [wangeditor-team/we-2021#201]
## bug 描述
<img width="1131" alt="截屏2021-09-11 下午11 15 37" src="https://user-images.githubusercontent.com/34530234/132952629-2b357266-c21e-4d51-a81d-43062b7f5dea.png">

*插入一段mp4视频会报错*

## 你预期的样子是？

*不报错*

## 系统和浏览器及版本号

- mac
- "@wangeditor/editor-cattle": "^0.7.10",
- "@wangeditor/editor-for-vue": "^0.6.6"

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 插入链接为https://stream7.iqilu.com/10339/upload_transcode/202002/18/20200218114723HDu3hhxqIT.mp4 的视频
- 控制台报错

**Comment by wangfupeng1988** [comment]
是否合并了最新的 main 分支代码？
