### ISSUE TITLE
带有居中的h1在删除后留下了p居中且不能删除

### ISSUE THREAD

**Issue by shi-lai-mu** [wangeditor-team/we-2021#203]
## bug 描述

对创建编辑器时的「一行标题」h1进行删除内容操作，当删完 文字内容 后再次删除会只剩下一个居中的p标签，且不能将p删除
![image](https://user-images.githubusercontent.com/45140991/132968102-f60fef23-c11b-4b39-88bb-fd739ab6837c.png)

## 你预期的样子是？

无内容的h1再删除后应该被直接删除不留下p

## 系统和浏览器及版本号

- mac bigsur
- Chrome 93.0.4577

## wangEditor 版本

测试地址最新/main

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 对 创建编辑器 后的h1「一行标题」文本内容进行删除
- 只剩下一个h1没有内容时再次删除（会变成p且居中）

**Comment by wangfupeng1988** [comment]
这个符合预期。

你预期的“直接删除不留下p”这不可能，因为这是第一个元素。
