### ISSUE TITLE
Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement] 

### ISSUE THREAD

**Issue by didashine** [wangeditor-team/we-2021#225]
## bug 描述

在react中引入编辑器，使用官网示例demo组件[ https://www.wangeditor.com/v5/guide/for-frame.html#%E4%BD%BF%E7%94%A8 ]，放到antd的Modal中在Modal重新打开后会报这个错，打印查看执行到示例代码的unmount时候editor已经为null，查阅资料看到slate的issue下面有人反馈类似的问题，不知道在wangEditor中有什么方法可以规避这个问题。
在slate中找到的issue：ianstormtaylor/slate#4427

## 你预期的样子是？

无报错

## wangEditor 版本

"@wangeditor/editor": "^0.10.2",
"@wangeditor/editor-for-react": "^0.6.10",

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤

在ant Modal中使用编辑器随便输入些内容，关闭后再打开，输入任意内容都会不断报错

**Comment by a835100635** [comment]
![2021-10-19 10-36-22 2021-10-19 10_37_38](https://user-images.githubusercontent.com/65208676/137834590-976ed1f7-3092-4e2a-a3aa-f5a87384f58c.gif)
react、react+ts 分别测试了，版本跟你对齐了，并没有报其他的错误，也不影响其功能。
[代码参考](https://github.com/a835100635/antd-demo-ts) 可对比一下是否正确

**Comment by ifui** [comment]
> 可在onCancel、onOk事件中提前销毁编辑器示例，具体代码可以[参考demo](https://github.com/a835100635/antd-demo-ts)，可解决’Update findDocumentOrShadowRoot to return the root node instead of throwing unnecessarily‘错误提示

事实上新版本的`slate`已经修复了该问题，[直达链接](https://github.com/ianstormtaylor/slate/pull/4427/files)，[commit记录](https://github.com/ianstormtaylor/slate/commits/main?after=fece5c157099b5ddef9f6dc8d070f2fdb3724b90+104&branch=main)，麻烦更新一下`slate`版本

**Comment by wangfupeng1988** [comment]
@ifui 收到，感谢反馈~
