### ISSUE TITLE
 autofocus 为true时，editor.dangerouslyInsertHtml 插入不生效

### ISSUE THREAD

**Issue by chencheng666** [wangeditor-team/we-2021#475]
## autofocus 为false时，editor.dangerouslyInsertHtml 插入不生效

*配置文件的autofocus 为false时，editor.dangerouslyInsertHtml 插入不生效，设置内容不显示*

## 你预期的样子是？

*editor.dangerouslyInsertHtml 插入后显示内容，当设置成true后可以显示*

## 系统和浏览器及版本号

- 操作系统 mac m1 pro monterey
- 浏览器和版本 chrome 98

## wangEditor 版本

*v5 0.26*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤
（请告诉我们，如何最快的复现该 bug）

- 步骤一 配置文件的autofocus 为false时
- 步骤二 editor.dangerouslyInsertHtml 插入不生效
- 步骤三 设置内容不显示

**Comment by wangfupeng1988** [comment]
先执行 `editor.focus()` 在插入 HTML ，这样试一试吧。
https://www.wangeditor.com/v5/guide/API.html#focus

**Comment by chencheng666** [comment]
好的，收到



| |
15542389060
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月06日 21:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wangeditor-team/wangEditor-v5]  autofocus 为true时，editor.dangerouslyInsertHtml 插入不生效 (Issue #475) |

先执行 editor.focus() 在插入 HTML ，这样试一试吧。
https://www.wangeditor.com/v5/guide/API.html#focus
