### ISSUE TITLE
复制微信、QQ图片粘贴上传无法使用

### ISSUE THREAD

**Issue by shi-lai-mu** [wangeditor-team/we-2021#75]
## bug 描述
微信、QQ复制一个图片，编辑器内粘贴后 Edge是包网络错误应该是服务原因（但截图上传正常），但其他浏览器正常上传该图。safari粘贴时无报错也没响应，有一个本地的uuid图片请求
有问题的图片在chrome、firefox均正常

edge报错如图
![1627575154(1)](https://user-images.githubusercontent.com/45140991/127528695-e3984d26-776f-4437-ac15-3879b8f25172.jpg)

## 你预期的样子是？

edge、safari正常插入图片

## 浏览器及版本号

*请输入内容……*
Edg/91.0.864.48 

## wangEditor 版本
V5

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 微信邮件复制
- 编辑器内粘贴

**Comment by shi-lai-mu** [comment]
92.0.902.67 (官方内部版本) 无法复现未开防火墙

**Comment by leohai** [comment]
edge 92 没复现
