### ISSUE TITLE
edge浏览器 输入法输入文字删除后编辑器控制台报错

### ISSUE THREAD

**Issue by q378532364** [wangeditor-team/we-2021#86]
## bug 描述

输入法输入文字删除后编辑器控制台报错

## 你预期的样子是？

不报错

## 浏览器及版本号
Microsoft Edge
版本 92.0.902.67 (官方内部版本

## wangEditor 版本

v5

## 官网能否复现该 bug ？
能

## 最小成本的复现步骤
 
1. 清空所有文本
2.  输入123 
3.  全选
4.  切换输入法 随意输入一个字符
5.  然后删除这个字符 再输入报错

![image](https://user-images.githubusercontent.com/43435489/128624187-6900f36f-ab9e-42f1-bc4f-61665b5b0c3b.png)

**Comment by shi-lai-mu** [comment]
@q378532364 最新的版本好像已经被修复了，前几天还能复现的，你那边现在还能复现吗

**Comment by shi-lai-mu** [comment]
新版已修复
