### ISSUE TITLE
一次拖拽多张图片无法正常上传图片 控制台报错

### ISSUE THREAD

**Issue by q378532364** [wangeditor-team/we-2021#93]
## bug 描述

编辑器拖拽多张图片无效 控制台报错

## 你预期的样子是？

编辑器拖拽多张图片无效

## wangEditor 版本

v5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1. 拖拽3张图片到编辑器

![image](https://user-images.githubusercontent.com/43435489/128624799-f508584a-fd0d-44ae-ba34-3159c5053830.png)

**Comment by wangfupeng1988** [comment]
最新代码已修复
